image: golang:1.6
stages:
  - build
  - test

build-my-project:
  stage: build
  script:
    - cd $CURRENT_BUILD_PATH
    - go build

test-my-project:
  image: golang:1.6
  stage: test
  script:
    - cd $CURRENT_BUILD_PATH
    - go test -v ./...
    - go test -race  -i ./...
    - golint ./... && test -z "`golint ./...`"
    - go vet -n ./...	|| true
    - test -z "`find . -type f -name "*.go" | xargs gofmt -s -w`"
    - test -z "`find . -type f -name "*.go" | xargs goimports -w`"