image: golang:1.6
variables:
        GROUP_NAME: "abador"
        APP_NAME: "indexer"
        PROJECT_REPO: "git@github.com:abador/indexer.git"
stages:
  - build
  - test

build-my-project:
  stage: build
  script:
    - cd /builds/$GROUP_NAME/$APP_NAME
    - go build
    - go test -v ./...
    - go test -race  -i ./...
    - golint ./... && test -z "`golint ./...`"
    - go vet -n ./...	|| true
    - test -z "`find . -type f -name "*.go" | xargs gofmt -s -w`"
    - test -z "`find . -type f -name "*.go" | xargs goimports -w`"